# Setup
Source: https://pypi.org/project/Wikipedia-API/

In [18]:
!pip install wikipedia-api

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wikipedia-api in /usr/local/lib/python3.7/dist-packages (0.5.4)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from wikipedia-api) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->wikipedia-api) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->wikipedia-api) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->wikipedia-api) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->wikipedia-api) (1.24.3)

In [2]:
import wikipediaapi
import pandas as pd

pd.set_option('display.max_columns', None)
#pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Wikipedia

Let's go to Wikipedia and find a page that you would like to further understand. I will pick "Spice" page for this example: https://en.wikipedia.org/wiki/Spice

![picture](https://drive.google.com/uc?id=1UeGzVI9xT6kQ6Rr9HvDYoCz0-TpZYrWI)

In [5]:
# Define language and page
wiki = wikipediaapi.Wikipedia('en')
page_spice = wiki.page('Spice')

In [6]:
# Get title
page_spice.title

'Spice'

In [7]:
# Get summary: short description
page_spice.summary

"A spice is a seed, fruit, root, bark, or other plant substance primarily used for flavoring or coloring food. Spices are distinguished from herbs, which are the leaves, flowers, or stems of plants used for flavoring or as a garnish. Spices are sometimes used in medicine, religious rituals, cosmetics or perfume production. For example, vanilla is commonly used as an ingredient in fragrance manufacturing.A spice may be available in several forms: fresh, whole dried, or pre-ground dried. Generally, spices are dried. Spices may be ground into a powder for convenience. A whole dried spice has the longest shelf life, so it can be purchased and stored in larger amounts, making it cheaper on a per-serving basis. A fresh spice, such as ginger, is usually more flavorful than its dried form, but fresh spices are more expensive and have a much shorter shelf life. Some spices are not always available either fresh or whole, for example turmeric, and often must be purchased in ground form. Small seeds, such as fennel and mustard seeds, are often used both whole and in powder form.\nAlthough health benefits are often claimed for spices, there is currently not enough research conducted to prove these benefits.India contributes to 75% of global spice production. This is reflected culturally through their cuisine; historically, the spice trade developed throughout the Indian subcontinent, as well as in East Asia and the Middle East. Europe's demand for spices was among the economic and cultural factors that encouraged exploration in the early modern period."

In [12]:
print(page_spice.text)

A spice is a seed, fruit, root, bark, or other plant substance primarily used for flavoring or coloring food. Spices are distinguished from herbs, which are the leaves, flowers, or stems of plants used for flavoring or as a garnish. Spices are sometimes used in medicine, religious rituals, cosmetics or perfume production. For example, vanilla is commonly used as an ingredient in fragrance manufacturing.A spice may be available in several forms: fresh, whole dried, or pre-ground dried. Generally, spices are dried. Spices may be ground into a powder for convenience. A whole dried spice has the longest shelf life, so it can be purchased and stored in larger amounts, making it cheaper on a per-serving basis. A fresh spice, such as ginger, is usually more flavorful than its dried form, but fresh spices are more expensive and have a much shorter shelf life. Some spices are not always available either fresh or whole, for example turmeric, and often must be purchased in ground form. Small seeds, such as fennel and mustard seeds, are often used both whole and in powder form.
Although health benefits are often claimed for spices, there is currently not enough research conducted to prove these benefits.India contributes to 75% of global spice production. This is reflected culturally through their cuisine; historically, the spice trade developed throughout the Indian subcontinent, as well as in East Asia and the Middle East. Europe's demand for spices was among the economic and cultural factors that encouraged exploration in the early modern period.

Etymology
The word spice originated in Middle English which came from the Old French words espece, espis(c)e, and espis(c)e. According to the Middle English Dictionary, the Old French words came from Anglo-French spece; according to Merriam Webster, the Old-French words came from Anglo-French espece, and espis. Both publications agree that the Anglo-French words derived from Latin species. Middle English spice had its first known use as a noun in the 13th century.

History
Early history
The spice trade developed throughout the Indian subcontinent by at earliest 2000 BCE with cinnamon and black pepper, and in East Asia with herbs and pepper. The Egyptians used herbs for mummification and their demand for exotic spices and herbs helped stimulate world trade. By 1000 BCE, medical systems based upon herbs could be found in China, Korea, and India. Early uses were connected with magic, medicine, religion, tradition, and preservation.Cloves were used in Mesopotamia by 1700 BCE. The ancient Indian epic Ramayana mentions cloves. The Romans had cloves in the 1st century CE, as Pliny the Elder wrote about them. The earliest written records of spices come from ancient Egyptian, Chinese, and Indian cultures. The Ebers Papyrus from early Egypt dating from 1550 BCE describes some eight hundred different medicinal remedies and numerous medicinal procedures. Historians believe that nutmeg, which originates from the Banda Islands in Southeast Asia, was introduced to Europe in the 6th century BCE.Indonesian merchants traveled around China, India, the Middle East, and the east coast of Africa. Arab merchants facilitated the routes through the Middle East and India. This resulted in the Egyptian port city of Alexandria being the main trading center for spices. The most important discovery prior to the European spice trade was the monsoon winds (40 CE). Sailing from Eastern spice cultivators to Western European consumers gradually replaced the land-locked spice routes once facilitated by the Middle East Arab caravans.Spices were prominent enough in the ancient world that they are mentioned in the Old Testament. In Genesis, Joseph was sold into slavery by his brothers to spice merchants. In Exodus, manna is described as being similar to coriander in appearance. In the Song of Solomon, the male narrator compares his beloved to many saffron, cinnamon, and other spices.

Middle Ages
Spices were among the most demanded and expensive products available in Europe in the Middle Ages,[5] the most common being black pepper, cinnamon (and the cheaper alternative cassia), cumin, nutmeg, ginger and cloves. Given medieval medicine's main theory of humorism, spices and herbs were indispensable to balance "humors" in food,[6] a daily basis for good health at a time of recurrent pandemics. In addition to being desired by those using medieval medicine, the European elite also craved spices in the Middle Ages. An example of the European aristocracy's demand for spice comes from the King of Aragon, who invested substantial resources into bringing back spices to Spain in the 12th century. He was specifically looking for spices to put in wine, and was not alone among European monarchs at the time to have such a desire for spice.Spices were all imported from plantations in Asia and Africa, which made them expensive. From the 8th until the 15th century, the Republic of Venice held a monopoly on spice trade with the Middle East, using this position to dominate the neighboring Italian maritime republics and city-states. The trade made the region rich. It has been estimated that around 1,000 tons of pepper and 1,000 tons of the other common spices were imported into Western Europe each year during the Late Middle Ages. The value of these goods was the equivalent of a yearly supply of grain for 1.5 million people. The most exclusive was saffron, used as much for its vivid yellow-red color as for its flavor. Spices that have now fallen into obscurity in European cuisine include grains of paradise, a relative of cardamom which mostly replaced pepper in late medieval north French cooking, long pepper, mace, spikenard, galangal and cubeb.

Early modern period
Spain and Portugal were interested in seeking new routes to trade in spices and other valuable products from Asia. The control of trade routes and the spice-producing regions were the main reasons that Portuguese navigator Vasco da Gama sailed to India in 1499.[8] When da Gama discovered the pepper market in India, he was able to secure peppers for a much cheaper price than the ones demanded by Venice. At around the same time, Christopher Columbus returned from the New World. He described to investors new spices available there.Another source of competition in the spice trade during the 15th and 16th century was the Ragusans from the maritime republic of Dubrovnik in southern Croatia. The military prowess of Afonso de Albuquerque (1453–1515) allowed the Portuguese to take control of the sea routes to India. In 1506, he took the island of Socotra in the mouth of the Red Sea and, in 1507, Ormuz in the Persian Gulf. Since becoming the viceroy of the Indies, he took Goa in India in 1510, and Malacca on the Malay peninsula in 1511. The Portuguese could now trade directly with Siam, China, and the Maluku Islands.
With the discovery of the New World came new spices, including allspice, chili peppers, vanilla, and chocolate. This development kept the spice trade, with America as a latecomer with its new seasonings, profitable well into the 19th century.

Function
Spices are primarily used as food flavoring or to create variety. They are also used to perfume cosmetics and incense. At various periods, many spices have been believed to have medicinal value. Finally, since they are expensive, rare, and exotic commodities, their conspicuous consumption has often been a symbol of wealth and social class.

Preservative claim
It is often claimed that spices were used either as food preservatives or to mask the taste of spoiled meat, especially in the European Middle Ages. This is false. In fact, spices are rather ineffective as preservatives as compared to salting, smoking, pickling, or drying, and are ineffective in covering the taste of spoiled meat. Moreover, spices have always been comparatively expensive: in 15th century Oxford, a whole pig cost about the same as a pound of the cheapest spice, pepper. There is also no evidence of such use from contemporary cookbooks: "Old cookbooks make it clear that spices weren't used as a preservative. They typically suggest adding spices toward the end of the cooking process, where they could have no preservative effect whatsoever." Indeed, Cristoforo di Messisbugo suggested in the 16th century that pepper may speed up spoilage.Though some spices have antimicrobial properties in vitro, pepper—by far the most common spice—is relatively ineffective, and in any case, salt, which is far cheaper, is also far more effective.

Classification and types
Culinary herbs and spices
Botanical basis
Common spice mixtures
Handling
For ground spices, to grind a whole spice, the classic tool is mortar and pestle. Less labor-intensive tools are more common now: a microplane or fine grater can be used to grind small amounts; a coffee grinder is useful for larger amounts. A frequently used spice such as black pepper may merit storage in its own hand grinder or mill.
The flavor of a spice is derived in part from compounds (volatile oils) that oxidize or evaporate when exposed to air. Grinding a spice greatly increases its surface area and so increases the rates of oxidation and evaporation. Thus, the flavor is maximized by storing a spice whole and grinding when needed. The shelf life of a whole dry spice is roughly two years; of a ground spice roughly six months. The "flavor life" of a ground spice can be much shorter. Ground spices are better stored away from light.Some flavor elements in spices are soluble in water; many are soluble in oil or fat. As a general rule, the flavors from a spice take time to infuse into the food so spices are added early in preparation. This contrasts to herbs which are usually added late in preparation.

Salmonella contamination
A study by the Food and Drug Administration of shipments of spices to the United States during fiscal years 2007–2009 showed about 7% of the shipments were contaminated by Salmonella bacteria, some of it antibiotic-resistant. As most spices are cooked before being served salmonella contamination often has no effect, but some spices, particularly pepper, are often eaten raw and present at table for convenient use. Shipments from Mexico and India, a major producer, were the most frequently contaminated. Food irradiation is said to minimise this risk.

Health research
Spices have been claimed to have health effects during both ancient and current times; for example, in 2017, the Washington Post said spices put "a natural pharmacy in your kitchen". The supposed health benefits include antioxidant and anti-inflammatory effects, and benefits towards certain diseases. A 2019 systematic review looked at studies of 25 spices and concluded that there is not enough evidence yet to support these supposed benefits, and that "further work is needed". The review noted that many studies were conducted by administering capsule or "artificial" forms of the spices, but spices are not normally consumed in this manner, and are normally consumed along other foods. Spices may reduce the need for salt as a flavoring agent in dishes, which has cardiovascular benefits.

Production
Standardization
The International Organization for Standardization addresses spices and condiments, along with related food additives, as part of the International Classification for Standards 67.220 series.

Research
The Indian Institute of Spices Research in Kozhikode, Kerala, is devoted exclusively to conducting research for ten spice crops: black pepper, cardamom, cinnamon, clove, garcinia, ginger, nutmeg, paprika, turmeric, and vanilla.

Gallery
See also
List of Indian spices – Variety of spices grown across the Indian subcontinent
List of culinary herbs and spices
Outline of herbs and spices
Seasoning – Process of supplementing food via herbs, salts, or spices
Spice mix
Spice use in Antiquity

Notes
References
Further reading
Books
Czarra, Fred (2009). Spices: A Global History. Reaktion Books. p. 128. ISBN 978-1-86189-426-7.
Dalby, Andrew (2000). Dangerous Tastes: The Story of Spices. University of California Press. ISBN 978-0-520-23674-5.
Freedman, Paul (2008). Out of the East: Spices and the Medieval Imagination. Yale University Press. ISBN 978-0-300-21131-3.
Keay, John (2006). The Spice Route: A History. John Murray. ISBN 978-0-7195-6199-3.
Krondl, Michael (2008). The Taste of Conquest: The Rise and Fall of the Three Great Cities of Spice. Random House. ISBN 978-0-345-50982-6.
Miller, James Innes (1969). The spice trade of the Roman Empire, 29 B.C. to A.D. 641. Oxford: Clarendon P. ISBN 978-0-19-814264-5.
Morton, Timothy (2006). The Poetics of Spice: Romantic Consumerism and the Exotic. Cambridge University Press. ISBN 978-0-521-02666-6.
Seidemann, Johannes (2005). World Spice Plants: Economic Usage, Botany, Taxonomy. Springer. ISBN 978-3-540-22279-8.
Turner, Jack (2004). Spice: The History of a Temptation. Knopf. ISBN 978-0-375-40721-5.

In [24]:
print(page_spice.sections)

[Section: Etymology (1):
The word spice originated in Middle English which came from the Old French words espece, espis(c)e, and espis(c)e. According to the Middle English Dictionary, the Old French words came from Anglo-French spece; according to Merriam Webster, the Old-French words came from Anglo-French espece, and espis. Both publications agree that the Anglo-French words derived from Latin species. Middle English spice had its first known use as a noun in the 13th century.
Subsections (0):
, Section: History (1):

Subsections (3):
Section: Early history (2):
The spice trade developed throughout the Indian subcontinent by at earliest 2000 BCE with cinnamon and black pepper, and in East Asia with herbs and pepper. The Egyptians used herbs for mummification and their demand for exotic spices and herbs helped stimulate world trade. By 1000 BCE, medical systems based upon herbs could be found in China, Korea, and India. Early uses were connected with magic, medicine, religion, tradition, and preservation.Cloves were used in Mesopotamia by 1700 BCE. The ancient Indian epic Ramayana mentions cloves. The Romans had cloves in the 1st century CE, as Pliny the Elder wrote about them. The earliest written records of spices come from ancient Egyptian, Chinese, and Indian cultures. The Ebers Papyrus from early Egypt dating from 1550 BCE describes some eight hundred different medicinal remedies and numerous medicinal procedures. Historians believe that nutmeg, which originates from the Banda Islands in Southeast Asia, was introduced to Europe in the 6th century BCE.Indonesian merchants traveled around China, India, the Middle East, and the east coast of Africa. Arab merchants facilitated the routes through the Middle East and India. This resulted in the Egyptian port city of Alexandria being the main trading center for spices. The most important discovery prior to the European spice trade was the monsoon winds (40 CE). Sailing from Eastern spice cultivators to Western European consumers gradually replaced the land-locked spice routes once facilitated by the Middle East Arab caravans.Spices were prominent enough in the ancient world that they are mentioned in the Old Testament. In Genesis, Joseph was sold into slavery by his brothers to spice merchants. In Exodus, manna is described as being similar to coriander in appearance. In the Song of Solomon, the male narrator compares his beloved to many saffron, cinnamon, and other spices.
Subsections (0):

Section: Middle Ages (2):
Spices were among the most demanded and expensive products available in Europe in the Middle Ages,[5] the most common being black pepper, cinnamon (and the cheaper alternative cassia), cumin, nutmeg, ginger and cloves. Given medieval medicine's main theory of humorism, spices and herbs were indispensable to balance "humors" in food,[6] a daily basis for good health at a time of recurrent pandemics. In addition to being desired by those using medieval medicine, the European elite also craved spices in the Middle Ages. An example of the European aristocracy's demand for spice comes from the King of Aragon, who invested substantial resources into bringing back spices to Spain in the 12th century. He was specifically looking for spices to put in wine, and was not alone among European monarchs at the time to have such a desire for spice.Spices were all imported from plantations in Asia and Africa, which made them expensive. From the 8th until the 15th century, the Republic of Venice held a monopoly on spice trade with the Middle East, using this position to dominate the neighboring Italian maritime republics and city-states. The trade made the region rich. It has been estimated that around 1,000 tons of pepper and 1,000 tons of the other common spices were imported into Western Europe each year during the Late Middle Ages. The value of these goods was the equivalent of a yearly supply of grain for 1.5 million people. The most exclusive was saffron, used as much for its vivid yellow-red color as for its flavor. Spices that have now fallen into obscurity in European cuisine include grains of paradise, a relative of cardamom which mostly replaced pepper in late medieval north French cooking, long pepper, mace, spikenard, galangal and cubeb.
Subsections (0):

Section: Early modern period (2):
Spain and Portugal were interested in seeking new routes to trade in spices and other valuable products from Asia. The control of trade routes and the spice-producing regions were the main reasons that Portuguese navigator Vasco da Gama sailed to India in 1499.[8] When da Gama discovered the pepper market in India, he was able to secure peppers for a much cheaper price than the ones demanded by Venice. At around the same time, Christopher Columbus returned from the New World. He described to investors new spices available there.Another source of competition in the spice trade during the 15th and 16th century was the Ragusans from the maritime republic of Dubrovnik in southern Croatia. The military prowess of Afonso de Albuquerque (1453–1515) allowed the Portuguese to take control of the sea routes to India. In 1506, he took the island of Socotra in the mouth of the Red Sea and, in 1507, Ormuz in the Persian Gulf. Since becoming the viceroy of the Indies, he took Goa in India in 1510, and Malacca on the Malay peninsula in 1511. The Portuguese could now trade directly with Siam, China, and the Maluku Islands.
With the discovery of the New World came new spices, including allspice, chili peppers, vanilla, and chocolate. This development kept the spice trade, with America as a latecomer with its new seasonings, profitable well into the 19th century.
Subsections (0):
, Section: Function (1):
Spices are primarily used as food flavoring or to create variety. They are also used to perfume cosmetics and incense. At various periods, many spices have been believed to have medicinal value. Finally, since they are expensive, rare, and exotic commodities, their conspicuous consumption has often been a symbol of wealth and social class.
Subsections (1):
Section: Preservative claim (2):
It is often claimed that spices were used either as food preservatives or to mask the taste of spoiled meat, especially in the European Middle Ages. This is false. In fact, spices are rather ineffective as preservatives as compared to salting, smoking, pickling, or drying, and are ineffective in covering the taste of spoiled meat. Moreover, spices have always been comparatively expensive: in 15th century Oxford, a whole pig cost about the same as a pound of the cheapest spice, pepper. There is also no evidence of such use from contemporary cookbooks: "Old cookbooks make it clear that spices weren't used as a preservative. They typically suggest adding spices toward the end of the cooking process, where they could have no preservative effect whatsoever." Indeed, Cristoforo di Messisbugo suggested in the 16th century that pepper may speed up spoilage.Though some spices have antimicrobial properties in vitro, pepper—by far the most common spice—is relatively ineffective, and in any case, salt, which is far cheaper, is also far more effective.
Subsections (0):
, Section: Classification and types (1):

Subsections (3):
Section: Culinary herbs and spices (2):

Subsections (0):

Section: Botanical basis (2):

Subsections (0):

Section: Common spice mixtures (2):

Subsections (0):
, Section: Handling (1):
For ground spices, to grind a whole spice, the classic tool is mortar and pestle. Less labor-intensive tools are more common now: a microplane or fine grater can be used to grind small amounts; a coffee grinder is useful for larger amounts. A frequently used spice such as black pepper may merit storage in its own hand grinder or mill.
The flavor of a spice is derived in part from compounds (volatile oils) that oxidize or evaporate when exposed to air. Grinding a spice greatly increases its surface area and so increases the rates of oxidation and evaporation. Thus, the flavor is maximized by storing a spice whole and grinding when needed. The shelf life of a whole dry spice is roughly two years; of a ground spice roughly six months. The "flavor life" of a ground spice can be much shorter. Ground spices are better stored away from light.Some flavor elements in spices are soluble in water; many are soluble in oil or fat. As a general rule, the flavors from a spice take time to infuse into the food so spices are added early in preparation. This contrasts to herbs which are usually added late in preparation.
Subsections (1):
Section: Salmonella contamination (2):
A study by the Food and Drug Administration of shipments of spices to the United States during fiscal years 2007–2009 showed about 7% of the shipments were contaminated by Salmonella bacteria, some of it antibiotic-resistant. As most spices are cooked before being served salmonella contamination often has no effect, but some spices, particularly pepper, are often eaten raw and present at table for convenient use. Shipments from Mexico and India, a major producer, were the most frequently contaminated. Food irradiation is said to minimise this risk.
Subsections (0):
, Section: Health research (1):
Spices have been claimed to have health effects during both ancient and current times; for example, in 2017, the Washington Post said spices put "a natural pharmacy in your kitchen". The supposed health benefits include antioxidant and anti-inflammatory effects, and benefits towards certain diseases. A 2019 systematic review looked at studies of 25 spices and concluded that there is not enough evidence yet to support these supposed benefits, and that "further work is needed". The review noted that many studies were conducted by administering capsule or "artificial" forms of the spices, but spices are not normally consumed in this manner, and are normally consumed along other foods. Spices may reduce the need for salt as a flavoring agent in dishes, which has cardiovascular benefits.
Subsections (0):
, Section: Production (1):

Subsections (0):
, Section: Standardization (1):
The International Organization for Standardization addresses spices and condiments, along with related food additives, as part of the International Classification for Standards 67.220 series.
Subsections (0):
, Section: Research (1):
The Indian Institute of Spices Research in Kozhikode, Kerala, is devoted exclusively to conducting research for ten spice crops: black pepper, cardamom, cinnamon, clove, garcinia, ginger, nutmeg, paprika, turmeric, and vanilla.
Subsections (0):
, Section: Gallery (1):

Subsections (0):
, Section: See also (1):
List of Indian spices – Variety of spices grown across the Indian subcontinent
List of culinary herbs and spices
Outline of herbs and spices
Seasoning – Process of supplementing food via herbs, salts, or spices
Spice mix
Spice use in Antiquity
Subsections (0):
, Section: Notes (1):

Subsections (0):
, Section: References (1):

Subsections (0):
, Section: Further reading (1):

Subsections (1):
Section: Books (2):
Czarra, Fred (2009). Spices: A Global History. Reaktion Books. p. 128. ISBN 978-1-86189-426-7.
Dalby, Andrew (2000). Dangerous Tastes: The Story of Spices. University of California Press. ISBN 978-0-520-23674-5.
Freedman, Paul (2008). Out of the East: Spices and the Medieval Imagination. Yale University Press. ISBN 978-0-300-21131-3.
Keay, John (2006). The Spice Route: A History. John Murray. ISBN 978-0-7195-6199-3.
Krondl, Michael (2008). The Taste of Conquest: The Rise and Fall of the Three Great Cities of Spice. Random House. ISBN 978-0-345-50982-6.
Miller, James Innes (1969). The spice trade of the Roman Empire, 29 B.C. to A.D. 641. Oxford: Clarendon P. ISBN 978-0-19-814264-5.
Morton, Timothy (2006). The Poetics of Spice: Romantic Consumerism and the Exotic. Cambridge University Press. ISBN 978-0-521-02666-6.
Seidemann, Johannes (2005). World Spice Plants: Economic Usage, Botany, Taxonomy. Springer. ISBN 978-3-540-22279-8.
Turner, Jack (2004). Spice: The History of a Temptation. Knopf. ISBN 978-0-375-40721-5.
Subsections (0):
]

In [13]:
def print_sections(sections, level=0):
        for s in sections:
            print(level * "\t*", (s.title + ': '), s.text[0:100])
            print_sections(s.sections, level + 1)

In [27]:
print_sections(page_spice.sections, level=0)

 Etymology:  The word spice originated in Middle English which came from the Old French words espece, espis(c)e,
 History:
	* Early history:  The spice trade developed throughout the Indian subcontinent by at earliest 2000 BCE with cinnamon a
	* Middle Ages:  Spices were among the most demanded and expensive products available in Europe in the Middle Ages,[5
	* Early modern period:  Spain and Portugal were interested in seeking new routes to trade in spices and other valuable produ
 Function:  Spices are primarily used as food flavoring or to create variety. They are also used to perfume cosm
	* Preservative claim:  It is often claimed that spices were used either as food preservatives or to mask the taste of spoil
 Classification and types:
	* Culinary herbs and spices:
	* Botanical basis:
	* Common spice mixtures:
 Handling:  For ground spices, to grind a whole spice, the classic tool is mortar and pestle. Less labor-intensi
	* Salmonella contamination:  A study by the Food and Drug Administration of shipments of spices to the United States during fisca
 Health research:  Spices have been claimed to have health effects during both ancient and current times; for example,
 Production:
 Standardization:  The International Organization for Standardization addresses spices and condiments, along with relat
 Research:  The Indian Institute of Spices Research in Kozhikode, Kerala, is devoted exclusively to conducting r
 Gallery:
 See also:  List of Indian spices – Variety of spices grown across the Indian subcontinent
List of culinary herb
 Notes:
 References:
 Further reading:
	* Books:  Czarra, Fred (2009). Spices: A Global History. Reaktion Books. p. 128. ISBN 978-1-86189-426-7.
Dalby

In [14]:
# Get categories for a page
def page_categories(page):
        categories = page.categories
        for title in sorted(categories.keys()):
            print("%s: %s" % (title, categories[title]))


print("Categories")
page_categories(page_spice)

Categories
Category:All articles with unsourced statements: Category:All articles with unsourced statements (id: ??, ns: 14)
Category:Articles containing Latin-language text: Category:Articles containing Latin-language text (id: ??, ns: 14)
Category:Articles containing Middle English (1100-1500)-language text: Category:Articles containing Middle English (1100-1500)-language text (id: ??, ns: 14)
Category:Articles containing Old French (842-ca. 1400)-language text: Category:Articles containing Old French (842-ca. 1400)-language text (id: ??, ns: 14)
Category:Articles with BNF identifiers: Category:Articles with BNF identifiers (id: ??, ns: 14)
Category:Articles with GND identifiers: Category:Articles with GND identifiers (id: ??, ns: 14)
Category:Articles with HDS identifiers: Category:Articles with HDS identifiers (id: ??, ns: 14)
Category:Articles with J9U identifiers: Category:Articles with J9U identifiers (id: ??, ns: 14)
Category:Articles with LCCN identifiers: Category:Articles with LCCN identifiers (id: ??, ns: 14)
Category:Articles with NDL identifiers: Category:Articles with NDL identifiers (id: ??, ns: 14)
Category:Articles with NKC identifiers: Category:Articles with NKC identifiers (id: ??, ns: 14)
Category:Articles with short description: Category:Articles with short description (id: ??, ns: 14)
Category:Articles with unsourced statements from December 2009: Category:Articles with unsourced statements from December 2009 (id: ??, ns: 14)
Category:Articles with unsourced statements from November 2021: Category:Articles with unsourced statements from November 2021 (id: ??, ns: 14)
Category:Commons link from Wikidata: Category:Commons link from Wikidata (id: ??, ns: 14)
Category:Plant products: Category:Plant products (id: ??, ns: 14)
Category:Short description is different from Wikidata: Category:Short description is different from Wikidata (id: ??, ns: 14)
Category:Spices: Category:Spices (id: ??, ns: 14)
Category:Use mdy dates from December 2014: Category:Use mdy dates from December 2014 (id: ??, ns: 14)

# Collecting (labelled) data
Build a data frame for spices:
In an earlier exercise we built a spice recommender. There, the spice list input was made manually. Let's build it now using Wikipedia.
Link to "Spices" category page: https://en.wikipedia.org/wiki/Category:Spices

In [20]:
# Get members for a category together with a short description
def members_collector(category):
      mdict = {}
      categorymembers = category.categorymembers
      for c in categorymembers.values():
        if c.ns == 0:                                                            # Exclude categories within the category
          mdict[c.title] = c.summary
      return mdict

In [22]:
# Let's collect spice
spices = wiki.page("Category:Spices")
spices_dict = members_collector(spices)

In [32]:
spices.categorymembers

{'Spice': Spice (id: 26897, ns: 0),
 'Acorus calamus': Acorus calamus (id: 371540, ns: 0),
 'Adobo': Adobo (id: 1242340, ns: 0),
 'Aframomum corrorima': Aframomum corrorima (id: 25998011, ns: 0),
 'Aframomum melegueta': Aframomum melegueta (id: 294127, ns: 0),
 'Ajwain': Ajwain (id: 346860, ns: 0),
 'Aleppo pepper': Aleppo pepper (id: 8250188, ns: 0),
 'Alleppey Green Cardamom': Alleppey Green Cardamom (id: 38291751, ns: 0),
 'Alligator pepper': Alligator pepper (id: 12395897, ns: 0),
 'Allspice': Allspice (id: 194873, ns: 0),
 'Alpinia caerulea': Alpinia caerulea (id: 18414662, ns: 0),
 'Alpinia galanga': Alpinia galanga (id: 5863248, ns: 0),
 'Alpinia nigra': Alpinia nigra (id: 38529280, ns: 0),
 'Alpinia officinarum': Alpinia officinarum (id: 9167550, ns: 0),
 'Amchoor': Amchoor (id: 3767418, ns: 0),
 'Amomum ovoideum': Amomum ovoideum (id: 52307157, ns: 0),
 'Angostura bitters': Angostura bitters (id: 1919281, ns: 0),
 'Anise': Anise (id: 68674, ns: 0),
 'Annatto': Annatto (id: 304091, ns: 0),
 'Asafoetida': Asafoetida (id: 193366, ns: 0),
 'List of Australian herbs and spices': List of Australian herbs and spices (id: 6516852, ns: 0),
 'Backhousia myrtifolia': Backhousia myrtifolia (id: 6437765, ns: 0),
 'Balsam of Peru': Balsam of Peru (id: 4267751, ns: 0),
 'Beau Monde seasoning': Beau Monde seasoning (id: 44957228, ns: 0),
 'Berberis vulgaris': Berberis vulgaris (id: 4231503, ns: 0),
 'Big Jim pepper': Big Jim pepper (id: 62607469, ns: 0),
 "Bird's eye chili": Bird's eye chili (id: 47850086, ns: 0),
 'Black cardamom': Black cardamom (id: 60953, ns: 0),
 'Boesenbergia rotunda': Boesenbergia rotunda (id: 165352, ns: 0),
 'Brassica nigra': Brassica nigra (id: 1729972, ns: 0),
 'Bunium bulbocastanum': Bunium bulbocastanum (id: 2363994, ns: 0),
 'Bunium luristanicum': Bunium luristanicum (id: 54986044, ns: 0),
 'Burlap & Barrel': Burlap & Barrel (id: 67509013, ns: 0),
 'Camphor': Camphor (id: 275978, ns: 0),
 'Camphora officinarum': Camphora officinarum (id: 2077266, ns: 0),
 'Candy cap': Candy cap (id: 8751138, ns: 0),
 'Canella': Canella (id: 24640562, ns: 0),
 'Caper': Caper (id: 309317, ns: 0),
 'Caraway': Caraway (id: 173546, ns: 0),
 'Cardamom': Cardamom (id: 60951, ns: 0),
 'Carissa carandas': Carissa carandas (id: 11545292, ns: 0),
 'Catechu': Catechu (id: 442617, ns: 0),
 'Cayenne pepper': Cayenne pepper (id: 47862531, ns: 0),
 'Celery': Celery (id: 6535, ns: 0),
 'Celery powder': Celery powder (id: 44956560, ns: 0),
 'Chicory': Chicory (id: 163617, ns: 0),
 'Chili powder': Chili powder (id: 1067344, ns: 0),
 'Chimayo pepper': Chimayo pepper (id: 54601877, ns: 0),
 'Cinnamomum burmannii': Cinnamomum burmannii (id: 8616210, ns: 0),
 'Cinnamomum cassia': Cinnamomum cassia (id: 460587, ns: 0),
 'Cinnamomum osmophloeum': Cinnamomum osmophloeum (id: 17716492, ns: 0),
 'Cinnamomum tenuifolium': Cinnamomum tenuifolium (id: 17715959, ns: 0),
 'Cinnamon': Cinnamon (id: 53469, ns: 0),
 'Clove': Clove (id: 70950, ns: 0),
 'Coriander': Coriander (id: 341640, ns: 0),
 'Crab boil': Crab boil (id: 5817897, ns: 0),
 'Cumin': Cumin (id: 47863730, ns: 0),
 'Curcuma zedoaria': Curcuma zedoaria (id: 882389, ns: 0),
 'Cymbopetalum costaricense': Cymbopetalum costaricense (id: 47328665, ns: 0),
 'Cymbopetalum penduliflorum': Cymbopetalum penduliflorum (id: 47370133, ns: 0),
 'Dalea lasiathera': Dalea lasiathera (id: 39200067, ns: 0),
 'Dill': Dill (id: 7985, ns: 0),
 'Dipteryx odorata': Dipteryx odorata (id: 2347991, ns: 0),
 'Ditaxis heterantha': Ditaxis heterantha (id: 25029304, ns: 0),
 'Dolomiaea costus': Dolomiaea costus (id: 15723157, ns: 0),
 'Dried lime': Dried lime (id: 3316320, ns: 0),
 'Drimys winteri': Drimys winteri (id: 9310367, ns: 0),
 'Elettaria cardamomum': Elettaria cardamomum (id: 7351937, ns: 0),
 'Elwendia persica': Elwendia persica (id: 2050856, ns: 0),
 'Euphorbia serpyllifolia': Euphorbia serpyllifolia (id: 21776209, ns: 0),
 'Fennel': Fennel (id: 173548, ns: 0),
 'Fenugreek': Fenugreek (id: 289834, ns: 0),
 'Fenugreek production in India': Fenugreek production in India (id: 50711242, ns: 0),
 'Fresno chile': Fresno chile (id: 22700180, ns: 0),
 'Galangal': Galangal (id: 65452, ns: 0),
 'Garam masala': Garam masala (id: 194874, ns: 0),
 'Garcinia gummi-gutta': Garcinia gummi-gutta (id: 1652560, ns: 0),
 'Garcinia indica': Garcinia indica (id: 30862510, ns: 0),
 'Garlic': Garlic (id: 50469, ns: 0),
 'Garlic oil': Garlic oil (id: 56165366, ns: 0),
 'Garlic powder': Garlic powder (id: 4143236, ns: 0),
 'Gaultheria procumbens': Gaultheria procumbens (id: 1460555, ns: 0),
 'Ginger': Ginger (id: 54929, ns: 0),
 'Grains of Selim': Grains of Selim (id: 30856597, ns: 0),
 'Heracleum persicum': Heracleum persicum (id: 18550056, ns: 0),
 'Horseradish': Horseradish (id: 45714, ns: 0),
 'Illicium verum': Illicium verum (id: 192575, ns: 0),
 'Jakhya': Jakhya (id: 57208620, ns: 0),
 'Jerk (cooking)': Jerk (cooking) (id: 1027441, ns: 0),
 'Juniper berry': Juniper berry (id: 6135482, ns: 0),
 'Kaffir lime': Kaffir lime (id: 196782, ns: 0),
 'Kala namak': Kala namak (id: 235441, ns: 0),
 'Leptotes bicolor': Leptotes bicolor (id: 23321926, ns: 0),
 'Liquorice': Liquorice (id: 249116, ns: 0),
 'List of mustard brands': List of mustard brands (id: 40977220, ns: 0),
 'Long pepper': Long pepper (id: 3072461, ns: 0),
 'Mahleb': Mahleb (id: 3059257, ns: 0),
 'Malagueta pepper': Malagueta pepper (id: 481232, ns: 0),
 'Mastic (plant resin)': Mastic (plant resin) (id: 26294679, ns: 0),
 'Monodora myristica': Monodora myristica (id: 12724408, ns: 0),
 'Mustard (condiment)': Mustard (condiment) (id: 30860614, ns: 0),
 'Mustard seed': Mustard seed (id: 187774, ns: 0),
 'Myrrh': Myrrh (id: 96861, ns: 0),
 'Nardostachys jatamansi': Nardostachys jatamansi (id: 37756813, ns: 0),
 'New Mexico chile': New Mexico chile (id: 45351270, ns: 0),
 'New Mexico No. 9': New Mexico No. 9 (id: 66601047, ns: 0),
 'Nigella arvensis': Nigella arvensis (id: 68770545, ns: 0),
 'Nigella sativa': Nigella sativa (id: 2043244, ns: 0),
 'Nutmeg': Nutmeg (id: 38546, ns: 0),
 'Onion powder': Onion powder (id: 3112548, ns: 0),
 'Orange bitters': Orange bitters (id: 9297530, ns: 0),
 'Osmundea pinnatifida': Osmundea pinnatifida (id: 29607034, ns: 0),
 'Pandanus amaryllifolius': Pandanus amaryllifolius (id: 5876840, ns: 0),
 'Parmotrema perlatum': Parmotrema perlatum (id: 28661667, ns: 0),
 'Pectis papposa': Pectis papposa (id: 30081430, ns: 0),
 'Penzeys Spices': Penzeys Spices (id: 35728307, ns: 0),
 'Pepper-dulse': Osmundea pinnatifida (id: 60597578, ns: 0),
 'Black pepper': Black pepper (id: 150116, ns: 0),
 'Peri-peri': Peri-peri (id: 2704726, ns: 0),
 'Persicaria hydropiper': Persicaria hydropiper (id: 2723209, ns: 0),
 'Phyllanthus emblica': Phyllanthus emblica (id: 1954027, ns: 0),
 'Pink peppercorn': Pink peppercorn (id: 6942489, ns: 0),
 'Piper borbonense': Piper borbonense (id: 31202823, ns: 0),
 'Piper cubeba': Piper cubeba (id: 2871685, ns: 0),
 'Piper excelsum': Piper excelsum (id: 2231612, ns: 0),
 'Piper guineense': Piper guineense (id: 12869270, ns: 0),
 'Pistacia lentiscus': Pistacia lentiscus (id: 60840, ns: 0),
 'Poppy seed': Poppy seed (id: 8768043, ns: 0),
 'Porophyllum ruderale': Porophyllum ruderale (id: 1137419, ns: 0),
 'Rhus coriaria': Rhus coriaria (id: 28289028, ns: 0),
 'Ricinodendron': Ricinodendron (id: 2526671, ns: 0),
 'Rosa × damascena': Rosa × damascena (id: 5407502, ns: 0),
 'Saffron': Saffron (id: 53332, ns: 0),
 'Use of saffron': Use of saffron (id: 13490464, ns: 0),
 'Saigon cinnamon': Saigon cinnamon (id: 3345254, ns: 0),
 'Sancho (spice)': Sancho (spice) (id: 71034736, ns: 0),
 'Sandia pepper': Sandia pepper (id: 62596034, ns: 0),
 'Santa Fe Grande': Santa Fe Grande (id: 2834697, ns: 0),
 'Scoville scale': Scoville scale (id: 43036, ns: 0),
 'Seasoning': Seasoning (id: 52863, ns: 0),
 'Sesame': Sesame (id: 82420, ns: 0),
 'Shan Foods': Shan Foods (id: 12024176, ns: 0),
 'Siling haba': Siling haba (id: 24838364, ns: 0),
 'Siling labuyo': Siling labuyo (id: 7930439, ns: 0),
 'Silphium': Silphium (id: 301024, ns: 0),
 'Smilax aristolochiifolia': Smilax aristolochiifolia (id: 35693734, ns: 0),
 'Smilax ornata': Smilax ornata (id: 499809, ns: 0),
 'Solanum centrale': Solanum centrale (id: 1651116, ns: 0),
 'Solo garlic': Solo garlic (id: 3049489, ns: 0),
 'Spice trade': Spice trade (id: 506548, ns: 0),
 'The Spice Trail': The Spice Trail (id: 31143928, ns: 0),
 'Spiced wine': Spiced wine (id: 39283150, ns: 0),
 'Spikenard': Spikenard (id: 30871887, ns: 0),
 'Sumac': Sumac (id: 69232, ns: 0),
 'Syzygium anisatum': Syzygium anisatum (id: 6168007, ns: 0),
 'Tagetes patula': Tagetes patula (id: 2067372, ns: 0),
 'Tamarind': Tamarind (id: 227931, ns: 0),
 'Tasmannia lanceolata': Tasmannia lanceolata (id: 4036289, ns: 0),
 'Tasmannia stipitata': Tasmannia stipitata (id: 6717485, ns: 0),
 'Trachyspermum roxburghianum': Trachyspermum roxburghianum (id: 1969613, ns: 0),
 'Trigonella caerulea': Trigonella caerulea (id: 40102507, ns: 0),
 'Turmeric': Turmeric (id: 29973, ns: 0),
 'Urfa biber': Urfa biber (id: 14372851, ns: 0),
 'Uzazi': Uzazi (id: 12348988, ns: 0),
 'Vanilla': Vanilla (id: 32623, ns: 0),
 'Wasabi': Wasabi (id: 33637, ns: 0),
 'White mustard': White mustard (id: 2729793, ns: 0),
 'Wurfbainia villosa': Wurfbainia villosa (id: 37725231, ns: 0),
 'Xiao mi la pepper': Xiao mi la pepper (id: 71384497, ns: 0),
 'Xylopia aethiopica': Xylopia aethiopica (id: 3009226, ns: 0),
 'Zanthoxylum acanthopodium': Zanthoxylum acanthopodium (id: 36450694, ns: 0),
 'Zanthoxylum armatum': Zanthoxylum armatum (id: 31758505, ns: 0),
 'Zanthoxylum piperitum': Zanthoxylum piperitum (id: 35245121, ns: 0),
 'Zingiber': Zingiber (id: 521948, ns: 0),
 'Category:Anise': Category:Anise (id: ??, ns: 14),
 'Category:Celery': Category:Celery (id: ??, ns: 14),
 'Category:Cinnamon': Category:Cinnamon (id: ??, ns: 14),
 'Category:Ginger': Category:Ginger (id: ??, ns: 14),
 'Category:Indian spices': Category:Indian spices (id: ??, ns: 14),
 'Category:Liquorice': Category:Liquorice (id: ??, ns: 14),
 'Category:Myrrh': Category:Myrrh (id: ??, ns: 14),
 'Category:Pakistani spices': Category:Pakistani spices (id: ??, ns: 14),
 'Category:Peppers': Category:Peppers (id: ??, ns: 14),
 'Category:Saffron': Category:Saffron (id: ??, ns: 14),
 'Category:Sri Lankan spices': Category:Sri Lankan spices (id: ??, ns: 14)}

In [35]:
spices_dict['White mustard']

'White mustard (Sinapis alba) is an annual plant of the family Brassicaceae. It is sometimes also referred to as Brassica alba or B. hirta. Grown for its seeds, used to make the condiment mustard, as fodder crop, or as a green manure, it is now widespread worldwide, although it probably originated in the Mediterranean region.'

In [43]:
# Create dataframe
spices_df = pd.DataFrame([spices_dict.keys(), spices_dict.values()]).T
spices_df.columns = ['Name', 'Description']
# spices_df = spices_df.style.set_properties(**{'text-align': 'left'}).set_table_styles([dict(selector='th', props=[('text-align', 'left')])])
# spices_df.to_csv('data/spices.csv')
spices_df

,Name,Description
0,Spice,"A spice is a seed, fruit, root, bark, or other plant substance primarily used for flavoring or coloring food. Spices are distinguished from herbs, which are the leaves, flowers, or stems of plants used for flavoring or as a garnish. Spices are sometimes used in medicine, religious rituals, cosmetics or perfume production. For example, vanilla is commonly used as an ingredient in fragrance manufacturing.A spice may be available in several forms: fresh, whole dried, or pre-ground dried. Generally, spices are dried. Spices may be ground into a powder for convenience. A whole dried spice has the longest shelf life, so it can be purchased and stored in larger amounts, making it cheaper on a per-serving basis. A fresh spice, such as ginger, is usually more flavorful than its dried form, but fresh spices are more expensive and have a much shorter shelf life. Some spices are not always available either fresh or whole, for example turmeric, and often must be purchased in ground form. Small seeds, such as fennel and mustard seeds, are often used both whole and in powder form.\nAlthough health benefits are often claimed for spices, there is currently not enough research conducted to prove these benefits.India contributes to 75% of global spice production. This is reflected culturally through their cuisine; historically, the spice trade developed throughout the Indian subcontinent, as well as in East Asia and the Middle East. Europe's demand for spices was among the economic and cultural factors that encouraged exploration in the early modern period."
1,Acorus calamus,"Acorus calamus (also called sweet flag, sway or muskrat root, among many common names) is a species of flowering plant with psychoactive chemicals. It is a tall wetland monocot of the family Acoraceae, in the genus Acorus. Although used in traditional medicine over centuries to treat digestive disorders and pain, there is no clinical evidence for its safety or efficacy – and ingested calamus may be toxic – leading to its commercial ban in the United States."
2,Adobo,"Adobo or adobar (Spanish: marinade, sauce, or seasoning) is the immersion of cooked food in a stock (or sauce) composed variously of paprika, oregano, salt, garlic, and vinegar to preserve and enhance its flavor. The Portuguese variant is known as Carne de vinha d'alhos. The practice, native to Iberia (Spanish cuisine and Portuguese cuisine), was widely adopted in Latin America, as well as Spanish and Portuguese colonies in Africa and Asia.\nIn the Philippines, the name adobo was given by colonial-era Spaniards on the islands to a different indigenous cooking method that also uses vinegar. Although similar, this developed independently of Spanish influence."
3,Aframomum corrorima,"Aframomum corrorima is a species of flowering plant in the ginger family, Zingiberaceae. It's a herbaceous perennial that produces leafy stems 1–2 meters tall from rhizomatous roots. The alternately-arranged leaves are dark green, 10–30 cm long and 2.5–6 cm across, elliptical to oblong in shape. Pink flowers are borne near the ground and give way to red, fleshy fruits containing shiny brown seeds, which are typically 3–5 mm in diameter.The spice, known as Ethiopian cardamom, false cardamom, or korarima, is obtained from the plant's seeds (usually dried), and is extensively used in Ethiopian and Eritrean cuisine. It is an ingredient in berbere, mitmita, awaze, and other spice mixtures, and is also used to flavor coffee. Its flavor is comparable to that of the closely related Elettaria cardamomum or green cardamom. In Ethiopian herbal medicine, the seeds are used as a tonic, carminative, and laxative.The plant is native to Tanzania, western Ethiopia (in the vicinity of Lake Tana and Gelemso), southwestern Sudan, western Uganda. It is cultivated in both Ethiopia and Eritrea, although the fruits are typically harvested from wild plants. The dried fruits are widely sold in markets and are relatively expensive, while fresh fruits are sold in production areas.In dried seeds and pods, the major oil components are 1,8-cineole (eucalyptol) and (E)-nerolidol. In fresh seeds, the major component of the essential oil is 1,8-cineole, followed by sabinene and geraniol. In fresh pods, the major oil constituents are γ-terpinene, β-pinene, α-phellandrene, 1,8-cineole, and p-cymene."
4,Aframomum melegueta,"Aframomum melegueta is a species in the ginger family, Zingiberaceae, and closely related to cardamom. Its seeds are used as a spice (ground or whole); it imparts a pungent, black-pepper-like flavor with hints of citrus. It is commonly known as grains of paradise, melegueta pepper, Guinea grains, ossame, or fom wisa, and is confused with alligator pepper. The term Guinea pepper has also been used, but is most often applied to Xylopia aethiopica (grains of Selim).\nIt is native to West Africa, which is sometimes named the Pepper Coast (or Grain Coast) because of this commodity. It is also an important cash crop in the Basketo district of southern Ethiopia."
...,...,...
168,Xylopia aethiopica,"Xylopia aethiopica is an evergreen, aromatic tree, of the Annonaceae family that can grow up to 20m high. It is a native to the lowland rainforest and moist fringe forests in the savanna zones of Africa.\nThe dried fruits of X. aethiopica (grains of Selim) are used as a spice and an herbal medicine."
169,Zanthoxylum acanthopodium,"Zanthoxylum acanthopodium, or andaliman, is a species of flowering plant in the family Rutaceae. Its range includes southern western China (Guangxi, Guizhou, Sichuan, Tibet, and Yunnan), Bangladesh, Bhutan, northern India and northeastern India (Arunachal Pradesh, Assam, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Uttar Pradesh, and West Bengal), Nepal, Laos, Burma, northern Thailand, Vietnam, Indonesia (northern Sumatran highlands), and Peninsular Malaysia.Much like the closely related Sichuan pepper (Z. piperitum), the seed pericarps are used as spices in cooking and have a similar tongue-numbing characteristic. However, in cooking, the flavour of andaliman has lemon-like notes (similar to those of lemon-grass) as well as a hint of the aromatic pandan leaf.\n\n\n== References =="
170,Zanthoxylum armatum,"Zanthoxylum armatum, also called winged prickly ash or rattan pepper in English, is a species of plant in the family Rutaceae. It is an aromatic, deciduous, spiny shrub growing to 3.5 metres (11 ft) in height, endemic from Pakistan across to Southeast Asia and up to Korea and Japan. It is one of the sources of the spice Sichuan pepper, and also used in folk medicine, essential oil production and as an ornamental garden plant."
171,Zanthoxylum piperitum,"Zanthoxylum piperitum, also known as Japanese pepper or Japanese prickly-ash is a deciduous aromatic spiny shrub or small tree of the citrus and rue family Rutaceae, native to Japan and Korea.\nIt is called sanshō (山椒) in Japan and chopi (초피) in Korea. Both the leaves and fruits (peppercorns) are used as an aromatic and flavoring in these countries. It is closely related to the Chinese Szechuan peppers, which come from plants of the same genus."
172,Zingiber,"The genus Zingiber is native to Southeast Asia especially in Thailand, China, the Indian Subcontinent, and New Guinea. It contains the true gingers, plants grown the world over for their culinary value. The most well known are Z. officinale and Z. mioga, two garden gingers."

In [26]:
type(spices_df)

pandas.io.formats.style.Styler

In [28]:
# Let's check favourite spice(s)
spices_df.data.query("Name=='Jakhya'")

,Name,Description
87,Jakhya,"Jakhya (Hindi: जख्या; Urdu: زخیا) (also called dog mustard or wild mustard) is the seed of the Cleome viscosa plant used for tempering on culinary dishes. It is mostly grown and consumed in Uttarakhand and in the Terai regions of India and Nepal.The seeds are dark brown in color, and crackles on being heated in oil. It is used in the Garhwali and Kumaoni styles of cuisines.\n\n\n== References =="

# ✨ Try at home✨
Well, herbs are not spices according to Wikipedia. But I really think we use them similarly when cooking. Can you now extract all herbs too to make our (imagined) recommender better?

In [ ]:
# Let's collect herbs
# Add your code here

In [ ]:
# Let's check out the herbs' dataframe
# Add your code here

In [ ]:
# Let's check favourite herb(s)
# Add your code here

# References

- https://phpenthusiast.com/blog/what-is-rest-api
- https://github.com/siznax/wptools/wiki/Data-captured
- https://en.wikipedia.org/w/api.php
- https://wikipedia.readthedocs.io/en/latest/code.html